### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ghost** [jerrymakesjelly/electricity-monitor#1]
python3 run.py没有使用其他选项报了如下的错误（myusername替换了目录名），不知道该怎么解决？是缺少这个.log文件还是Python版本的问题？我有安装Anaconda，在MacOS和Linux下都报这个错。

```
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    ap = animateprogress.AnimateProgress()
  File "/Users/myusername/Downloads/electricity-monitor/animateprogress.py", line 10, in __init__
    self._logger = logger.register(__name__)
  File "/Users/myusername/Downloads/electricity-monitor/logger.py", line 27, in register
    fh = logging.FileHandler(os.path.join(REAL_PATH, LOG_FILE_PATH))
  File "/Users/myusername/anaconda3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/myusername/anaconda3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/myusername/Downloads/electricity-monitor/log/electricity-monitor.log'
```

**Comment by jerrymakesjelly** [comment]
由于git不会提交空目录到仓库中导致目录不存在，是我的问题 = =

在electricity-monitor目录下创建一个空白的log目录即可

**Comment by ghost** [comment]
添加了log目录就可以了，感谢回复。
